alias ls='ls --color=auto'
alias dotdrop='{{@@ _dotdrop_dotpath @@}}/programs/dotdrop/dotdrop.sh -c ../../config.yaml -b'
alias ncmpcpp='ncmpcpp -b ${XDG_CONFIG_HOME:-$HOME/.config}/ncmpcpp/bindings'
alias tb='taskbook'
alias tmux='tmux -f ~/.config/tmux/tmux.conf'
